---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
  labels:
    app: provider
spec:
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider
        image: snazzybucket/provider:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            port: 8080
            path: "/health"
---
apiVersion: v1
kind: Service
metadata:
  name: provider
  labels:
    app: provider
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: provider
---
