name: Docker Image CI

on:
  push:
    branches: '**'

jobs:
  build-docker-images:
    strategy:
      matrix:
        service: [antaeus, provider, testclient]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the ${{ matrix.service }} Docker image
      run: make docker-build-${{ matrix.service }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: |
        docker push snazzybucket/${{ matrix.service }}:latest
  test-k8s-dhall:
    needs: [build-docker-images]
    runs-on: ubuntu-latest
    name: test dhall on microk8s
    steps:
    - uses: actions/checkout@v2
    - uses: balchua/microk8s-actions@v0.2.2
      with:
        channel: '1.19/stable'
        addons: '["dns", "ingress"]'
    - name: start services
      id: myactions
      run: |
        kubectl get no
        kubectl get pods -A -o wide
        make render-k8s-yaml-docker
        make deploy
    - name: Test pay in k8s network
      id: test-in-cluster-network
      run: |
        kubectl run testclient --env="MAX_RETRIES=30" --env="API_URL=http://antaeus" --restart=Never --rm -i --image snazzybucket/testclient:latest
    - name: Print logs on failure
      if: ${{ failure() }}
      id: get-logs
      run: |
        kubectl logs -l app=antaeus
        kubectl logs -l app=provider
    - name: Test pay in via ingress
      id: test-in-with-ingress
      run: |
        docker run -e="API_URL=http://172.17.0.1:80" --rm snazzybucket/testclient:latest
