apiVersion: v1
kind: Service
metadata:
  name: pleo-antaeus
  labels:
    app: pleo-antaeus
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: pleo-antaeus
