apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleo-antaeus
  labels:
    app: pleo-antaeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pleo-antaeus
  template:
    metadata:
      labels:
        app: pleo-antaeus
    spec:
      containers:
      - name: pleo-antaeus
        image: faidonpassias/pleo-antaeus:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000
        env:
        - name: PAYMENT_PROVIDER_ENDPOINT
          value: http://payment-service.default.svc.cluster.local:9000
        readinessProbe:
          httpGet:
            path: /rest/health
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /rest/health
            port: 8000
          initialDelaySeconds: 240
          timeoutSeconds: 3
          periodSeconds: 15
