apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleo-payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment-image:latest 
        ports:
        - containerPort: 9000



