apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleo-payment
  labels:
    app: pleo-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: faidonpassias/pleo-payment:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15


