apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleo-antaeusdep
  labels:
    app: pleo-antaeusdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pleo-antaeus
  template:
    metadata:
      labels:
        app: pleo-antaeus
    spec:
      containers:
      - name: pleo-antaeus
        image: faidonpassias/magicalantaeus
        ports:
        - containerPort: 8000
        env:
        - name: PAYMENT_PROVIDER_ENDPOINT
          value: http://payment-service.default.svc.cluster.local:9000
